SELECT years_on_force,
        AVG(allegation_count) as avg_total,
        AVG(year_zero_allegation_count) as year_zero,
        AVG(year_one_allegation_count) as year_one,
        AVG(year_two_allegation_count)  as year_two,
        AVG(year_three_allegation_count) as year_three,
        AVG(year_four_allegation_count) as year_four,
        AVG(year_five_allegation_count) as year_five,
        AVG(year_six_allegation_count)  as year_six,
        AVG(year_seven_allegation_count) as year_seven,
        AVG(year_eight_allegation_count) as year_eight,
        AVG(year_nine_allegation_count) as year_nine,
        AVG(year_ten_allegation_count) as year_ten,
        AVG(year_eleven_allegation_count) as year_eleven,
        AVG(year_twelve_allegation_count) as year_twelve,
        AVG(year_thirteen_allegation_count) as year_thirteen,
        AVG(year_fourteen_allegation_count) as year_fourteen,
        AVG(year_fifteen_allegation_count)  as year_fifteen,
        AVG(year_sixteen_allegation_count) as year_sixteen,
        AVG(year_seventeen_allegation_count) as year_seventeen,
        AVG(year_eighteen_allegation_count)  as year_eighteen,
        AVG(year_nineteen_allegation_count)  as year_nineteen,
        AVG(year_twenty_allegation_count) as year_twenty
FROM officer_subset
GROUP BY years_on_force;